# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_signup_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
