# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170317_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
